<?php

namespace common\models\fibos;

use yii\behaviors\TimestampBehavior;

/**
 * EOS/FO 兑换比率
 *
 * Class ExchangeInfo
 * @package common\models\fibos
 *
 * @property integer price
 */
class ExchangeInfo extends \strong\models\base\Mysql
{
    public function behaviors()
    {
//        return parent::behaviors(); // TODO: Change the autogenerated stub
        return [
            //自动处理创建/修改时间
            [
                'class' => TimestampBehavior::class,
                //                'createdAtAttribute' => 'created_at',
                                'updatedAtAttribute' => false,
                //'value' => new Expression('NOW()'),
                //'value'=>$this->timeTemp(),
            ],

        ];
    }
}